### ISSUE TITLE
CRUD: selectAll returns 'null'

### ISSUE THREAD

**Issue by devmaaj** [jeremias-joao/Projecto-Java-JDBC-MySQL-JavaFX#1]
Ao tentar executar o metodo br.uninove.poo.persistencia.ClienteDAO.buscarTudo() a aplicação quebra devido a declaração do retorno como arraylist sem tipo definido.

**Comment by vmaffioli** [comment]
Mude o tipo de  retorno do metodo buscarTudo de ArrayList para ArrayList<Cliente>

**Comment by vmaffioli** [comment]
Enviei o PullRequest contendo a correção, inseri o tipo correto para o arraylist declarado.

**Comment by vmaffioli** [comment]
Unforking project, details have been tought trought linkedin, the owner accepts the helps but have closed both issue and PR.
Leaving.
